logrec_definition =  {
'thsum': ['domain', 'receive_time', 'serial', 'app', 'src', 'dst', 'rule', 'threatid', 'subtype', 'srcuser', 'dstuser', 'vsys', 'from', 'to', 'srcloc', 'dstloc', 'sessions', 'tunneled-app', 'technology-of-app', 'category-of-app', 'subcategory-of-app', 'risk-of-app', 'severity-of-threatid'], 
'appstat': ['domain', 'receive_time', 'serial', 'timestamp', 'vsys', 'name', 'risk', 'type', 'nbytes', 'nsess', 'npkts', 'nthreats', 'tunneled-name', 'technology-of-name', 'category-of-name', 'subcategory-of-name', 'risk-of-name'],
'system': ['domain', 'receive_time', 'serial', 'type', 'subtype', 'config_ver', 'time_generated', 'vsys', 'eventid', 'object', 'fmt', 'id', 'module', 'severity', 'opaque'], 
'trsum': ['domain', 'receive_time', 'serial', 'app', 'src', 'dst', 'rule', 'srcuser', 'dstuser', 'category', 'vsys', 'from', 'to', 'bytes', 'sessions', 'srcloc', 'dstloc', 'tunneled-app', 'technology-of-app', 'category-of-app', 'subcategory-of-app', 'risk-of-app'],
'traffic': ['domain', 'receive_time', 'serial', 'type', 'subtype', 'config_ver', 'time_generated', 'src', 'dst', 'natsrc', 'natdst', 'rule', 'srcuser', 'dstuser', 'app', 'vsys', 'from', 'to', 'inbound_if', 'outbound_if', 'logset', 'time_received', 'sessionid', 'repeatcnt', 'sport', 'dport', 'natsport', 'natdport', 'flags', 'proto', 'action', 'bytes', 'bytes_sent', 'bytes_received', 'packets', 'start', 'elapsed', 'category', 'padding', 'tunneled-app', 'technology-of-app', 'category-of-app', 'subcategory-of-app', 'risk-of-app'], 
'threat': ['domain', 'receive_time', 'serial', 'type', 'subtype', 'config_ver', 'time_generated', 'src', 'dst', 'natsrc', 'natdst', 'rule', 'srcuser', 'dstuser', 'app', 'vsys', 'from', 'to', 'inbound_if', 'outbound_if', 'logset', 'time_received', 'sessionid', 'repeatcnt', 'sport', 'dport', 'natsport', 'natdport', 'flags', 'proto', 'action', 'misc', 'threatid', 'category', 'severity', 'direction', 'tunneled-app', 'technology-of-app', 'category-of-app', 'subcategory-of-app', 'risk-of-app', 'severity-of-threatid'], 
'data': ['domain', 'receive_time', 'serial', 'type', 'subtype', 'config_ver', 'time_generated', 'src', 'dst', 'natsrc', 'natdst', 'rule', 'srcuser', 'dstuser', 'app', 'vsys', 'from', 'to', 'inbound_if', 'outbound_if', 'logset', 'time_received', 'sessionid', 'repeatcnt', 'sport', 'dport', 'natsport', 'natdport', 'flags', 'proto', 'action', 'misc', 'threatid', 'category', 'severity', 'direction', 'tunneled-app', 'technology-of-app', 'category-of-app', 'subcategory-of-app', 'risk-of-app', 'severity-of-threatid'], 
'url': ['domain', 'receive_time', 'serial', 'type', 'subtype', 'config_ver', 'time_generated', 'src', 'dst', 'natsrc', 'natdst', 'rule', 'srcuser', 'dstuser', 'app', 'vsys', 'from', 'to', 'inbound_if', 'outbound_if', 'logset', 'time_received', 'sessionid', 'repeatcnt', 'sport', 'dport', 'natsport', 'natdport', 'flags', 'proto', 'action', 'misc', 'threatid', 'category', 'severity', 'direction', 'tunneled-app', 'technology-of-app', 'category-of-app', 'subcategory-of-app', 'risk-of-app', 'severity-of-threatid'], 
'config': ['domain', 'receive_time', 'serial', 'type', 'subtype', 'config_ver', 'time_generated', 'host', 'vsys', 'cmd', 'admin', 'client', 'result', 'path'],
'hipmatch': ['domain','receive_time','serial','type','subtype','config_ver','time_generated','src','srcuser','vsys','machinename','matchname','matchtype']}